# Usar a imagem base do NGINX
FROM nginx:alpine

# Copiar os arquivos do frontend (HTML, CSS, JS)
COPY . /usr/share/nginx/html

# Expor a porta padrão do NGINX
EXPOSE 80

# NGINX já inicia automaticamente